version: '2'
services:
  app-app:
    image: app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://app-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://app-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://app-elasticsearch:9200
      - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true
    ports:
      - 8080:8080
  app-mongodb:
    extends:
      file: mongodb.yml
      service: app-mongodb
  app-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: app-elasticsearch
